export const DEMO_TOURS = [
  {
    _id: 'demo-tour-1',
    title: 'Khatu Shyam Ji – Salasar Balaji – Rani Sati Yatra',
    description: 'एक अद्भुत यात्रा जो आपको खाटू श्याम जी, सालासर बालाजी और रानी सती धाम तक ले जाएगी। यह तीर्थयात्रा आपके जीवन की सबसे यादगार आध्यात्मिक अनुभव होगी।',
    route: 'Khatu Shyam Ji → Salasar Balaji → Rani Sati Jhunjhunur',
    startDate: new Date('2026-07-11').toISOString(),
    endDate: new Date('2026-07-12').toISOString(),
    price: 1500,
    services: ['AC Bus', 'Breakfast', 'Lunch', 'Water Bottle & Refreshments'],
    inclusions: [
      'AC Bus transportation',
      'Breakfast on Day 1',
      'Lunch on Day 2',
      'Water bottles & snacks',
      'Experienced guide',
      'All temple entry fees',
    ],
    pickupPoints: [
      'Sector 52, Noida – Metro Pillar No. 657 (08:30 PM)',
      'Sector 18, Noida – Atta Market (08:45 PM)',
      'Delhi – Akshardham (09:15 PM)',
    ],
    image: '',
    departureTime: '08:30 PM',
    totalSeats: 50,
    availableSeats: 23,
    status: 'upcoming',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-tour-2',
    title: 'Vrindavan – Mathura – Gokul Yatra',
    description: 'भगवान श्री कृष्ण की लीलाभूमि वृंदावन, मथुरा और गोकुल की पावन यात्रा। बांके बिहारी, कृष्ण जन्मभूमि और यमुना स्नान का अद्भुत अवसर।',
    route: 'Vrindavan → Mathura → Gokul',
    startDate: new Date('2026-08-05').toISOString(),
    endDate: new Date('2026-08-06').toISOString(),
    price: 1200,
    services: ['AC Bus', 'Breakfast', 'Lunch', 'Water Bottle'],
    inclusions: [
      'AC Bus transportation',
      'Breakfast & Lunch',
      'Water bottles',
      'Hotel stay (1 night)',
      'Local guide',
    ],
    pickupPoints: [
      'Sector 52, Noida – Metro Pillar No. 657 (07:00 AM)',
      'Sector 18, Noida – Atta Market (07:15 AM)',
    ],
    image: '',
    departureTime: '07:00 AM',
    totalSeats: 45,
    availableSeats: 31,
    status: 'upcoming',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-tour-3',
    title: 'Haridwar – Rishikesh Yatra',
    description: 'गंगा स्नान, हर की पौड़ी गंगा आरती और ऋषिकेश में लक्ष्मण झूला का दर्शन। यह यात्रा आपके मन और आत्मा को शांति प्रदान करेगी।',
    route: 'Haridwar → Rishikesh',
    startDate: new Date('2026-09-14').toISOString(),
    endDate: new Date('2026-09-15').toISOString(),
    price: 1800,
    services: ['AC Bus', 'Breakfast', 'Lunch', 'Water Bottle', 'Hotel Stay'],
    inclusions: [
      'AC Volvo Bus',
      'Breakfast & Dinner',
      'Hotel accommodation',
      'Ganga Aarti darshan',
      'All transfers',
    ],
    pickupPoints: [
      'Sector 52, Noida – Metro Pillar No. 657 (06:00 AM)',
    ],
    image: '',
    departureTime: '06:00 AM',
    totalSeats: 40,
    availableSeats: 18,
    status: 'upcoming',
    featured: false,
    createdAt: new Date().toISOString(),
  },
]
