const img = (id: string) => `https://images.unsplash.com/${id}?w=900&q=80&auto=format&fit=crop`

const DEMO_QR = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="220" height="220"><rect width="220" height="220" fill="white"/><rect x="10" y="10" width="60" height="60" fill="black"/><rect x="25" y="25" width="30" height="30" fill="white"/><rect x="150" y="10" width="60" height="60" fill="black"/><rect x="165" y="25" width="30" height="30" fill="white"/><rect x="10" y="150" width="60" height="60" fill="black"/><rect x="25" y="165" width="30" height="30" fill="white"/><rect x="90" y="40" width="15" height="15" fill="black"/><rect x="120" y="40" width="15" height="15" fill="black"/><rect x="90" y="90" width="15" height="15" fill="black"/><rect x="120" y="90" width="15" height="15" fill="black"/><rect x="150" y="120" width="15" height="15" fill="black"/><rect x="90" y="150" width="15" height="15" fill="black"/><rect x="120" y="180" width="15" height="15" fill="black"/><rect x="180" y="150" width="15" height="15" fill="black"/></svg>'

export const DEMO_TOURS = [
  // ---------- SPIRITUAL ----------
  {
    _id: 'demo-tour-1',
    title: 'Khatu Shyam Ji – Salasar Balaji – Rani Sati Yatra',
    description: 'एक अद्भुत यात्रा जो आपको खाटू श्याम जी, सालासर बालाजी और रानी सती धाम तक ले जाएगी। यह तीर्थयात्रा आपके जीवन की सबसे यादगार आध्यात्मिक अनुभव होगी।',
    route: 'Khatu Shyam Ji → Salasar Balaji → Rani Sati Jhunjhunur',
    startDate: new Date('2026-07-11').toISOString(),
    endDate: new Date('2026-07-12').toISOString(),
    price: 1500,
    category: 'spiritual',
    services: ['AC Bus', 'Breakfast', 'Lunch', 'Water Bottle & Refreshments'],
    inclusions: ['AC Bus transportation', 'Breakfast on Day 1', 'Lunch on Day 2', 'Water bottles & snacks', 'Experienced guide', 'All temple entry fees'],
    pickupPoints: ['Sector 52, Noida – Metro Pillar No. 657 (08:30 PM)', 'Sector 18, Noida – Atta Market (08:45 PM)', 'Delhi – Akshardham (09:15 PM)'],
    image: img('photo-1605649487212-47bdab064df7'),
    qrImage: DEMO_QR,
    paymentNote: 'Demo QR — please call 9773834051 once before payment, then send the payment screenshot to confirm.',
    departureTime: '08:30 PM',
    totalSeats: 50,
    availableSeats: 23,
    status: 'upcoming',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-tour-2',
    title: 'Vrindavan – Mathura – Gokul Yatra',
    description: 'भगवान श्री कृष्ण की लीलाभूमि वृंदावन, मथुरा और गोकुल की पावन यात्रा। बांके बिहारी, कृष्ण जन्मभूमि और यमुना स्नान का अद्भुत अवसर।',
    route: 'Vrindavan → Mathura → Gokul',
    startDate: new Date('2026-08-05').toISOString(),
    endDate: new Date('2026-08-06').toISOString(),
    price: 1200,
    category: 'spiritual',
    services: ['AC Bus', 'Breakfast', 'Lunch', 'Water Bottle'],
    inclusions: ['AC Bus transportation', 'Breakfast & Lunch', 'Water bottles', 'Hotel stay (1 night)', 'Local guide'],
    pickupPoints: ['Sector 52, Noida – Metro Pillar No. 657 (07:00 AM)', 'Sector 18, Noida – Atta Market (07:15 AM)'],
    image: img('photo-1604608672516-f1b9b1d37076'),
    departureTime: '07:00 AM',
    totalSeats: 45,
    availableSeats: 31,
    status: 'upcoming',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-tour-3',
    title: 'Haridwar – Rishikesh Yatra',
    description: 'गंगा स्नान, हर की पौड़ी गंगा आरती और ऋषिकेश में लक्ष्मण झूला का दर्शन। यह यात्रा आपके मन और आत्मा को शांति प्रदान करेगी।',
    route: 'Haridwar → Rishikesh',
    startDate: new Date('2026-09-14').toISOString(),
    endDate: new Date('2026-09-15').toISOString(),
    price: 1800,
    category: 'spiritual',
    services: ['AC Bus', 'Breakfast', 'Lunch', 'Water Bottle', 'Hotel Stay'],
    inclusions: ['AC Volvo Bus', 'Breakfast & Dinner', 'Hotel accommodation', 'Ganga Aarti darshan', 'All transfers'],
    pickupPoints: ['Sector 52, Noida – Metro Pillar No. 657 (06:00 AM)'],
    image: img('photo-1561361513-2d000a50f0dc'),
    departureTime: '06:00 AM',
    totalSeats: 40,
    availableSeats: 18,
    status: 'upcoming',
    featured: false,
    createdAt: new Date().toISOString(),
  },

  // ---------- LEISURE / ADVENTURE ----------
  {
    _id: 'demo-tour-4',
    title: 'Manali – Solang Valley Adventure',
    description: 'बर्फ से ढके पहाड़, सोलंग वैली में एडवेंचर और हिडिम्बा मंदिर का दर्शन। मनाली की खूबसूरत वादियों में एक यादगार सफर — परिवार और दोस्तों के साथ।',
    route: 'Delhi → Manali → Solang Valley → Rohtang',
    startDate: new Date('2026-07-20').toISOString(),
    endDate: new Date('2026-07-24').toISOString(),
    price: 8500,
    category: 'leisure',
    services: ['AC Volvo Bus', 'Hotel Stay (3 Nights)', 'Breakfast & Dinner', 'Sightseeing'],
    inclusions: ['AC Volvo round trip', '3-star hotel (3 nights)', 'Daily breakfast & dinner', 'Solang Valley visit', 'Hidimba Temple & Mall Road', 'All sightseeing by cab'],
    pickupPoints: ['Sector 52, Noida – Metro Pillar No. 657 (05:00 PM)', 'Delhi – Kashmere Gate (06:00 PM)'],
    image: img('photo-1626621341517-bbf3d9990a23'),
    departureTime: '05:00 PM',
    totalSeats: 35,
    availableSeats: 20,
    status: 'upcoming',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-tour-5',
    title: 'Mussoorie – Queen of Hills Getaway',
    description: 'मसूरी की ठंडी हवाएं, केम्प्टी फॉल, माल रोड और गन हिल की सैर। पहाड़ों की रानी मसूरी में 2 रातों का सुकून भरा प्रवास।',
    route: 'Delhi → Mussoorie → Kempty Falls',
    startDate: new Date('2026-08-15').toISOString(),
    endDate: new Date('2026-08-17').toISOString(),
    price: 6500,
    category: 'leisure',
    services: ['AC Bus', 'Hotel Stay (2 Nights)', 'Breakfast', 'Sightseeing'],
    inclusions: ['AC Bus transport', 'Hotel (2 nights)', 'Daily breakfast', 'Kempty Falls', 'Gun Hill & Mall Road', 'Camel Back Road'],
    pickupPoints: ['Sector 52, Noida – Metro Pillar No. 657 (10:00 PM)'],
    image: img('photo-1593181629936-11c609b8db9b'),
    departureTime: '10:00 PM',
    totalSeats: 40,
    availableSeats: 28,
    status: 'upcoming',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-tour-6',
    title: 'Rishikesh – Dehradun River Rafting Trip',
    description: 'ऋषिकेश में रिवर राफ्टिंग, कैम्पिंग और देहरादून की सैर। एडवेंचर पसंद करने वालों के लिए perfect weekend getaway।',
    route: 'Delhi → Rishikesh → Dehradun',
    startDate: new Date('2026-09-05').toISOString(),
    endDate: new Date('2026-09-07').toISOString(),
    price: 5500,
    category: 'leisure',
    services: ['AC Bus', 'Camp Stay', 'River Rafting', 'Meals'],
    inclusions: ['AC Bus transport', 'Riverside camp (2 nights)', 'River rafting 16 km', 'Bonfire & music night', 'All meals', 'Robbers Cave Dehradun'],
    pickupPoints: ['Sector 52, Noida – Metro Pillar No. 657 (11:00 PM)'],
    image: img('photo-1571536802807-30451e3955d8'),
    departureTime: '11:00 PM',
    totalSeats: 30,
    availableSeats: 15,
    status: 'upcoming',
    featured: true,
    createdAt: new Date().toISOString(),
  },
]
